### ISSUE TITLE
Search bar z-index is higher than navbar dropdown menu.

### ISSUE THREAD

**Issue by folz** [chen-ye/hms-react#2]
![screen shot 2015-10-19 at 02 44 13](https://cloud.githubusercontent.com/assets/299281/10574523/55c09474-760b-11e5-93fd-797d164fa62e.png)

**Comment by chen-ye** [comment]
fixed... somehow?  I don't recall doing anything but ok

**Comment by chen-ye** [comment]
fixed as of 6bf90863465515fe71bcd6ff7a3adbea809bf03b
